include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
  exclude:
    - '**.g.dart'
    - '**.mocks.dart'
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    unawaited_futures: true
    always_declare_return_types: true
    use_full_hex_values_for_flutter_colors: true
    prefer_final_in_for_each: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: false