name: locale_gen
description: Dart tool that will convert your default locale json to dart code.
version: 3.3.0
homepage: https://github.com/vanlooverenkoen/locale_gen

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  meta: ^1.3.0
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.16.8