include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
  exclude:
    - "**.g.dart"
    - "**.config.dart"
    - "**.navigator.dart"
    - "**.mocks.dart"
  language:
    strict-casts: true
    strict-raw-types: true

formatter:
  trailing_commas: preserve

linter:
  rules:
    - unawaited_futures
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
