import 'package:locale_gen/src/util/format/locale_gen_file_util.dart';
import 'package:test/test.dart';

void main() {
  test('writeAutoGeneratedHeader writes the do-not-edit banner', () {
    final sb = StringBuffer();

    LocaleGenFileUtil.writeAutoGeneratedHeader(sb);

    expect(
      sb.toString(),
      '//============================================================//\n'
      '//THIS FILE IS AUTO GENERATED. DO NOT EDIT//\n'
      '//============================================================//\n',
    );
  });
}
