class LocaleGenFileUtil {
  const LocaleGenFileUtil._();

  /// 3-line `// AUTO GENERATED // DO NOT EDIT //` banner emitted at the top of
  /// every generated localization file.
  static void writeAutoGeneratedHeader(StringBuffer sb) {
    sb
      ..writeln(
          '//============================================================//')
      ..writeln('//THIS FILE IS AUTO GENERATED. DO NOT EDIT//')
      ..writeln(
          '//============================================================//');
  }
}
